### ISSUE TITLE
Can I use this with GHC 8.6?

### ISSUE THREAD

**Issue by kozross** [hdevtools/hdevtools#85] opened 2018-10-01 00:52 UTC
It would be really good if I could!

**Comment by kozross** [comment] 2018-10-30 21:17
``hdevtools-1.7.0`` fails to build on ``nightly-2018-10-30`` (assuming use of [this NMU][1]), with the following error message:

```
[ 4 of 14] Compiling Info             ( src/Info.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/hdevtools/hdevtools-tmp/Info.o )
    
    /tmp/stack17632/hdevtools-0.1.7.0/src/Info.hs:215:67: error:
        Not in scope: type constructor or class ‘GHC.PostTc’
        Module ‘GHC’ does not export ‘PostTc’.
        |
    215 |         postTcType = const (stage<TypeChecker)                 :: GHC.PostTc TypecheckI GHC.Type -> Bool
        |
```

[1]: http://hackage.haskell.org/package/polyparse-1.12.1

**Comment by stouf** [comment] 2019-01-04 10:06
Same error here using GHC 8.6.3 on Archlinux.

**Comment by drewboardman** [comment] 2019-02-10 00:20
Same error with Ubuntu 18.04

**Comment by xlxs4** [comment] 2019-03-01 19:06
Same error using GHC 8.6.3 on Arch.

**Comment by drewboardman** [comment] 2019-03-03 01:49
Any update on the progress of this?

**Comment by ch1bo** [comment] 2019-03-06 21:44
Merged ghc 8.6 support with #91, you should be able to try it on `master` now. I will cut a release soon, ideally after some of you guys report that it works!

**Comment by stouf** [comment] 2019-03-07 02:02
I just gave it a shot but it failed with the following 😢

```
Configuring hdevtools-0.1.7.0...
Preprocessing executable 'hdevtools' for hdevtools-0.1.7.0..
Building executable 'hdevtools' for hdevtools-0.1.7.0..
[ 1 of 14] Compiling Daemonize        ( src/Daemonize.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/hdevtools/hdevtools-tmp/Daemonize.o )
[ 2 of 14] Compiling GhcTypes         ( src/GhcTypes.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/hdevtools/hdevtools-tmp/GhcTypes.o )
[ 3 of 14] Compiling FindSymbol       ( src/FindSymbol.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/hdevtools/hdevtools-tmp/FindSymbol.o )
[ 4 of 14] Compiling Info             ( src/Info.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/hdevtools/hdevtools-tmp/Info.o )

src/Info.hs:215:67: error:
    Not in scope: type constructor or class ‘GHC.PostTc’
    Module ‘GHC’ does not export ‘PostTc’.
    |
215 |         postTcType = const (stage<TypeChecker)                 :: GHC.PostTc TypecheckI GHC.Type -> Bool
    |
```

Some extra information:

- Operating system: Archlinux
- Text editor: vim / https://github.com/bitc/vim-hdevtools
- GHC v8.6.3
- Stack v1.9.3
- Resolver used in the project: lts-13.5

**Comment by ch1bo** [comment] 2019-03-07 05:33
Make sure you try to compile the newest version. I did increment the project version to 0.1.8.0, so your log is from an older commit.

**Comment by stouf** [comment] 2019-03-07 05:54
> Make sure you try to compile the newest version. I did increment the project version to 0.1.8.0, so your log is from an older commit

Whoops, nevermind, v0.1.8.0 seems to work for me :+1: 
The reason why I had the logs above is because `vim-hdevtools` had [the `g:hdevtools_stack` option](https://github.com/bitc/vim-hdevtools#local-hdevtools-with-stack) on, so it was using v0.1.7.0. Nothing related to v0.1.8.0.

**Comment by stouf** [comment] 2019-03-10 10:15
I ran into an issue today. I'm not sure if it's related to this issue but here is what I observed:

- the project I'm working in uses `stack` with the resolver [`lts-13.5`](https://www.stackage.org/lts-13.5)
- `lts-13.5` contains the version 0.10.10 of `hedis`
- given that I want to use the version 0.12.0 of `hedis`, I installed it through adding the corresponding commit hash to the `extra-deps` property of the `stack.yaml` file of the project
- when trying to get type information about something, I get the following error message:
  ```
  Cabal error: hdevtools: Encountered missing dependencies:
  hedis ==0.12.0 
  ```
- I made sure the version 0.12.0 of `hedis` has been installed in my `~/.stack` folder
- if I use the version 0.10.10 of `hedis`, `hdevtools` works as expected

Could it be related to this issue?

**Comment by xlxs4** [comment] 2019-03-10 13:30
Now works on Arch.

**Comment by ch1bo** [comment] 2019-03-10 21:24
Released 0.1.8.0 on hackage https://hackage.haskell.org/package/hdevtools, which includes ghc 8.6 support and should be available in the stackage nightlies soon (then `stack install hdevtools --resolver nightly` installs this version). Until then, only `cabal install hdevtools` or building with checked out repo will get you the newest version.

**Comment by ch1bo** [comment] 2019-03-10 21:25
> I ran into an issue today. I'm not sure if it's related to this issue but here is what I observed:
> 
> * the project I'm working in uses `stack` with the resolver [`lts-13.5`](https://www.stackage.org/lts-13.5)
> * `lts-13.5` contains the version 0.10.10 of `hedis`
> * given that I want to use the version 0.12.0 of `hedis`, I installed it through adding the corresponding commit hash to the `extra-deps` property of the `stack.yaml` file of the project
> * when trying to get type information about something, I get the following error message:
>   ```
>   Cabal error: hdevtools: Encountered missing dependencies:
>   hedis ==0.12.0 
>   ```
> * I made sure the version 0.12.0 of `hedis` has been installed in my `~/.stack` folder
> * if I use the version 0.10.10 of `hedis`, `hdevtools` works as expected
> 
> Could it be related to this issue?

Does `stack build` work in that scenario? How could I reproduce this - can you share a .cabal and .stack file? Maybe we should move that to a new issue as it is not ghc 8.6 related

**Closed by ch1bo** 2019-03-10 21:25 UTC

**Comment by stouf** [comment] 2019-03-11 14:23
> Does stack build work in that scenario?

Yep, it does :+1: 

> How could I reproduce this - can you share a .cabal and .stack file?

I tried to reproduce it on a different machine and noticed something that confirms it's not related to this issue, and maybe not even to `hdevtools` at all. I run my project in a docker container where `~/.stack` of the host (Archlinux system) is mounted on `~/.stack` in the container, and the root of the project on the home directory of the user in the container. When `hedis` has been built in the container, I get the error message I reported above. However, if I rebuild the project from the host, `hdevtools` starts working again. I'm not sure why yet, but one thing is sure: it's not something related to this issue.
I'll try to figure out why/how that happens and post an issue if it has something to do with `hdevtools`.
Anyway, sorry for the noise! 😅

**Comment by ch1bo** [comment] 2019-03-11 14:56
No worries.

You might want to check whether your container and host use a similar enough toolchain (not entirely sure how package databases are indexed). Alternative: also build and use hdevtools in a docker container (with the same base image).

**Comment by stouf** [comment] 2019-03-12 01:02
@ch1bo Thanks for the support 🙂

I figured it out. The answer was in the `.stack-work` folder in my project. To Stack, my host system and the operating system powering the [Docker image I use](https://docs.docker.com/samples/library/haskell/) are different and therefore libraries are installed in different folders (`.stack-work/install/x86_64-linux-tinfo6` for my host system and `stack-work/install/x86_64-linux` for the Docker container). As a result, when I use `hdevtools` from my host system, it expects the dependencies of my project to be installed in the folder related to the environment it runs in, which makes totally sense.

Sorry again for the noise. I just wanted to share my conclusion, in case someone else happens to run into the same problem. This should be my last message here 😅

> Alternative: also build and use hdevtools in a docker container (with the same base image).

Yep, I think that would work :+1:
